site_name: ' ' 
site_url: https://whyziks.github.io/croww/

theme: 
  name: material
  hide:
    - toc
  font:
    code: Jetbrains Mono
    text: Roboto
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.footer
  palette:
    scheme: slate
    primary: black
    accent: deep grey
extra_css: 
  - stylesheets/extra.css
nav:

   - 'Добро пожаловать!': 'index.md'
   - 'Правила': 'rules.md'
   - 'Крафты': 'crafts.md'
   - 'Команды': 'commands.md'
   - 'Фишки':
     - 'Показать ник': 'nickname.md'



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: /simple/discord
      link: https://discord.gg/fKPNDYVxjB
    - icon: simple/telegram
      link: https://t.me/croww_mc